# Generated by Django 4.2.16 on 2024-10-22 12:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todoapp", "0002_task_is_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2024, 10, 22, 12, 11, 52, 884050, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
    ]
