# Generated by Django 4.2.16 on 2024-10-22 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todoapp", "0004_alter_task_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
